# Generated by Django 4.2.6 on 2023-10-23 05:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'role',
            },
        ),
        migrations.RenameField(
            model_name='todo',
            old_name='created_time',
            new_name='createdTime',
        ),
        migrations.RenameField(
            model_name='todo',
            old_name='updated_time',
            new_name='updatedTime',
        ),
        migrations.RemoveField(
            model_name='todo',
            name='completed',
        ),
        migrations.AddField(
            model_name='todo',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='todo',
            name='nextTodo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='todo_api.todo'),
        ),
        migrations.AddField(
            model_name='todo',
            name='todoStatus',
            field=models.IntegerField(choices=[(1, 'Not started'), (2, 'In progress'), (3, 'Done')], default=1),
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('roles', models.ManyToManyField(to='todo_api.role')),
            ],
            options={
                'db_table': 'teamMember',
            },
        ),
        migrations.AddField(
            model_name='todo',
            name='teamMember',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='todo_api.teammember'),
            preserve_default=False,
        ),
    ]
