CREATE DATABASE USER_MANAGMENT

--1A
CREATE TABLE [USER] 
(
	ID INT IDENTITY(1,1) PRIMARY KEY, 
	FNAME VARCHAR(60) NOT NULL, 
	LNAME VARCHAR(60) NOT NULL, 
	EMAIL VARCHAR(255) NOT NULL UNIQUE, 
	USERNAME VARCHAR(60) NOT NULL UNIQUE, 
	PASSWORD VARCHAR(60) NOT NULL, 
	CREATION_DATE DATETIME
)

CREATE TABLE [ROLE]
(
	ID INT PRIMARY KEY, 
	NAME VARCHAR(60) NOT NULL UNIQUE
)

CREATE TABLE USER_ROLES
(
	[USER_ID] INT NOT NULL FOREIGN KEY REFERENCES [USER] ON DELETE CASCADE,
	ROLE_ID INT NOT NULL FOREIGN KEY REFERENCES [ROLE], 
	ADDED_DATE DATE, 
	PRIMARY KEY([USER_ID], ROLE_ID)
)

--1B
ALTER TABLE [USER]
ADD PHONE VARCHAR(60)

--1C
INSERT INTO [USER](FNAME, LNAME, EMAIL, USERNAME, PASSWORD, CREATION_DATE)
VALUES('IVAN', 'IVANOV', 'IVAN@GMAIL.COM','IVAN', '123456', GETDATE())

INSERT INTO [USER](FNAME, LNAME, EMAIL, USERNAME, PASSWORD, CREATION_DATE, PHONE)
VALUES('MARIA', 'DIMITROVA', 'MARIA@GMAIL.COM', 'MARIA', '123456', GETDATE(), '121451')

SELECT *
FROM [USER]

INSERT INTO [ROLE]
VALUES(10, 'USER')

INSERT INTO [ROLE]
VALUES(20, 'ADMIN')

SELECT *
FROM [ROLE]

INSERT INTO USER_ROLES
VALUES(1, 20, GETDATE())

INSERT INTO USER_ROLES
VALUES(2, 10, GETDATE())

SELECT *
FROM USER_ROLES

--1D
UPDATE USER_ROLES
SET ROLE_ID = 20
WHERE [USER_ID] = 2

--1E
DELETE FROM [USER]
WHERE CONVERT(DATE,CREATION_DATE) = '2016-02-15'

DELETE FROM [USER]
WHERE CONVERT(DATE,CREATION_DATE) = '2021-11-25'

--2A
SELECT JOB_TITLE 
FROM JOBS 
WHERE MIN_SALARY > 7000 AND MAX_SALARY < 16000
ORDER BY JOB_TITLE DESC

SELECT *
FROM JOBS

--2B
SELECT SUM(UNIT_PRICE * QUANTITY) AS TOTAL 
FROM ORDERS O JOIN ORDER_ITEMS OI 
ON O.ORDER_ID = OI.ORDER_ID
WHERE ORDER_DATE > '2000-05-01'

--2C
SELECT FNAME, LNAME, ORDER_ID, MIN(ORDER_DATE) AS FIRST_ORD
FROM CUSTOMERS C JOIN ORDERS O
ON C.CUSTOMER_ID = O.CUSTOMER_ID
WHERE GENDER = 'M'
GROUP BY FNAME, LNAME, ORDER_ID

--2D
SELECT NAME, SUM(QUANTITY) AS TOTAL 
FROM PRODUCTS P JOIN ORDER_ITEMS OI 
ON P.PRODUCT_ID = OI.PRODUCT_ID
JOIN ORDERS O 
ON O.ORDER_ID = OI.ORDER_ID
WHERE MONTH(ORDER_DATE) = 3 AND YEAR(ORDER_DATE) = 2000
GROUP BY NAME

--3
CREATE VIEW DEP_SALARY_VIEW
AS
SELECT NAME, AVG(SALARY) AS AVG_SALARY 
FROM DEPARTMENTS D JOIN EMPLOYEES E 
ON D.DEPARTMENT_ID = E.DEPARTMENT_ID
GROUP BY NAME 

SELECT *
FROM DEP_SALARY_VIEW

