/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package myapp;

import org.eclipse.collections.api.factory.primitive.IntLists;
import org.eclipse.collections.api.list.primitive.MutableIntList;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
    	MutableIntList intList = IntLists.mutable.of(1,2,3,4,5);
    	
    	intList.add(10);
    	
    	intList.forEach(n -> System.out.println(n));
    	
        System.out.println(new App().getGreeting());
    }
}
