/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package di;

public class App {
    public static void main(String[] args) {

        String[] emailSubscribers = {
            "katya@gmail.com", "martin@gmail.com", "_______@example.com", "mihail+mihailov@abv.bg", ".invalid@mail.com", "@invalidexample.com"
        };
        String[] smsSubscribers = {
            "+359891234567", "+35988NotValid", "1-391-555-1943", "+12345678901234567"
        };

        try {
            var emailProcessor = new MessageProcessor(null);
            emailProcessor.processMessage(
                "Store successfully started automatically scheduled discount!",
                "admin@store.com"
            );
        } catch (Exception e) {
            System.out.println("Couldn't send email to admin about store discount.");
            // write to log
            // e.printStackTrace();
        }
        
        String discountMessage = "Our store has a new discount, check it out!";

        FlexibleMessageProcessor messageProcessor;
        try {
            messageProcessor = new FlexibleMessageProcessor();
        } catch (Exception e) {
            System.out.println("Couldn't send discount notifications.");
            // write to log
            // e.printStackTrace();
            return;
        }

        for (String email : emailSubscribers) {
            try {
                messageProcessor.processEmailMessage(discountMessage + " Click here to unsubscibe.", email);
            } catch (Exception e) {
                System.out.println("Couldn't send discount email to " + email + ".");
                // write to log
                // e.printStackTrace();
            }
        }

        for (String phone : smsSubscribers) {
            try {
                messageProcessor.processSMSMessage(discountMessage + " Dial 1451 to unsubscribe.", phone);
            } catch (Exception e) {
                System.out.println("Couldn't send discount sms to " + phone + ".");
                // write to log
                // e.printStackTrace();
            }
        }
    }
}
